name: Test provider

on: push

env:
  GO_VERSION: "1.15"
  GO111MODULE: on
  CASSANDRA_HOST: localhost
  CASSANDRA_USERNAME: cassandra
  CASSANDRA_PASSWORD: cassandra

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cassandra_version: [2, 3]
        terraform_version: ["0.12.26", "0.12.29", "0.13.4", "latest", "default"]
    env:
      CASSANDRA_VERSION: ${{ matrix.cassandra_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v1
        with:
          terraform_version: ${{ matrix.terraform_version }}
          terraform_wrapper: false
        if: matrix.terraform_version != 'default'
      - run: make test
      - run: make vet
      - run: make testacc
