name: Test provider

on: push

env:
  GO_VERSION: "1.15"
  GO111MODULE: on
  CASSANDRA_HOST: localhost
  CASSANDRA_USERNAME: cassandra
  CASSANDRA_PASSWORD: cassandra

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cassandra_version: [2, 3]
    env:
      CASSANDRA_VERSION: ${{ matrix.cassandra_version }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - run: make test
      - run: make vet
      - run: make testacc
